### ISSUE TITLE
What exactly is test_cover_one_null testing?

### ISSUE THREAD

**Issue by cen1** [tubaman/mosaico-server-tests#3]
I am confused what the test test_cover_one_null is actually testing and what height being null actually means. If I do such a call to official node backend it returns a broken image: http://127.0.0.1:9006/img/?src=http://127.0.0.1:9006/uploads/I0T0.png&method=cover&params=190,null

So apparently even the official backend doesn't pass this test. As far as I understand, with both width and height defined the image is:
1. Proportionally scaled to the requested size (meaning, scaled either in width or height, depending on which scaling ratio is smaller)
2. Centrally cropped to fit the exact requested width and height.

Checking the node and PHP backend implementation, null would assumingly cause the height scaling to be ignored and the image would be proportionally scaled to the width parameter. This however fails with the `self.assertEqual(image.size, photo.size)` test which makes even less sense because the very definition of "cover" is that you try to best fit an image to a smaller, not-same-aspect-ratio box so there is no way it can stay the same size as the original.

Could someone clarify what the null height parameter is supposed to do?

**Comment by cen1** [comment]
Ok, apparently doing a simple GET request with the null parameter won't render in browser but it does work via Mosaico JS request. I'm still not sure how to implement the call though.

**Comment by tubaman** [comment]
The last official backend version I tested with, [v0.15](https://github.com/voidlabs/mosaico/releases/tag/v0.15), passes.  I've added that note to the [README](https://github.com/tubaman/mosaico-server-tests/commit/938864e).  Which official backend version are you testing against?

Just some background.  I needed this test suite because I'm the author of the [Django mosaico server](https://github.com/tubaman/django-mosaico).  I needed a way to verify that my Django server behaved the same as the node-based official server.  I just tried to duplicate the behavior of the official(node-based) mosaico server when I wrote the django-based one.

If either width or height is null, [I don't scale](https://github.com/tubaman/django-mosaico/commit/2424318).

**Comment by tubaman** [comment]
So, I don't think this is an issue with the tests so I'm going to close this.

**Comment by cen1** [comment]
Thanks for clarification. I used this tests to bring up a java backend, some things really confused me though because there is no 1:1 mapping in image functions if you compare PHP ImageMagick bindings, Node GraphicsMagick and native Java 2D calls.

After playing around more with official backend it seem that it scales to whatever parameter is available and then does the fit magic. 
&params=300,null reults in image with 300 width and height of whatever
&params=null,300 results in image with 300 height and width of whatever

When a param is missing it seems to become whatever width or height is needed to preserve the aspect ratio to not distort the image although I got some very weird results from official backend with black areas.. so I don't fully understand it really.

It seems that your python code before the patch you linked did exactly that but you decided to remove that and just not scale for some reason?

**Comment by tubaman** [comment]
Hrmm... I think that patch best replicated the response that I got from the official backend.  If that's not the case I can reinvestigate.

**Comment by bago** [comment]
a null parameter in width/height is permitted (and is the most expected use case) using the RESIZE method. The COVER method needs them both to be specified (covering an undefined area makes no sense).

**Comment by bago** [comment]
It is "documented" here: https://github.com/voidlabs/mosaico/blob/master/backend/README.txt
If you see a different behaviour from what is specified there, please let me know and I will doublecheck.

**Comment by cen1** [comment]
So that means that `test_cover_one_null` is testing undefined behavior and can be removed.

**Comment by cen1** [comment]
Indeed, cover with a null parameter does not make any sense so I guess `test_cover_one_null` can be removed. If Mosaico never sends such a request there is no need to test it or trying to mimic the node backend.

**Comment by tubaman** [comment]
Ok, you've convinced me.  Plus I can't figure out why I added that test in the first place.

https://github.com/tubaman/mosaico-server-tests/commit/ec1211ed295985b4aa8320ba24982c5851c9e7f0
